import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function Home() {
    return (
        <>
            {/* <style jsx global>{`
            .mySpan {
                color: red;
                font-weight: bold;
            }
            `}</style> */}
            <Head>
                <title>Hunting Coder</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <Script src="/abc.js" strategy="lazyOnload"></Script> */}
            <div
                className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
            >
                <main className={styles.main}>
                    <h1>
                        <span className="mySpan">Hunting Coder</span>
                    </h1>
                    <Image
                        className={styles.myImg}
                        src="/homeimg.jpeg"
                        height={300}
                        width={450}
                        alt="Home Image"
                    />
                    <p className="margin-bottom:50px">
                        A blog for coders by a coder.
                    </p>

                    <div className={styles.blogs}>
                        <h2>Popular blogs</h2>
                        <div className="blogItem" style={{ marginTop: "20px" }}>
                            <h3>How to learn JS ? </h3>
                            <p>Js is used for the backend of a website</p>
                        </div>
                        <div className="blogItem" style={{ marginTop: "20px" }}>
                            <h3>How to learn JS ? </h3>
                            <p>Js is used for the backend of a website</p>
                        </div>
                        <div className="blogItem" style={{ marginTop: "20px" }}>
                            <h3>How to learn JS ? </h3>
                            <p>Js is used for the backend of a website</p>
                        </div>
                    </div>
                </main>
                <footer className={styles.footer}></footer>
            </div>
        </>
    );
}
