import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function Home() {
    return (
        <>
            {/* <style jsx global>{`
            .mySpan {
                color: red;
                font-weight: bold;
            }
            `}</style> */}
            <Head>
                <title>Hunting Coder</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <Script src="/abc.js" strategy="lazyOnload"></Script> */}
            <div
                className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
            >
                <main className={styles.main}>
                    <h1 className={styles.title}>
                        <span className="mySpan">Hunting Coder</span>
                    </h1>
                    <Image
                        className={styles.myImg}
                        src="/homeimg.jpeg"
                        height={275}
                        width={275}
                        alt="Home Image"
                    />

                    <div className={styles.blogs}>
                        <h2>Latest Blogs</h2>
                        <div style={{ marginTop: "20px" }}>
                            <h3>How to learn JS ? </h3>
                            <p className={styles.p}>
                                Js is a programming language used for the
                                frontend of a website, it is used to make
                                websites interactive and dynamic.
                            </p>
                            <button className={styles.btn}>Read More</button>
                        </div>
                        <div style={{ marginTop: "20px" }}>
                            <h3>How to learn NextJS ? </h3>
                            <p className={styles.p}>
                                NextJS is a framework built on top of ReactJS
                                that allows for server-side rendering and static
                                site generation, making it easier to build fast
                                and scalable web applications.
                            </p>
                            <button className={styles.btn}>Read More</button>
                        </div>
                        <div style={{ marginTop: "20px" }}>
                            <h3>How to learn MongoDB ? </h3>
                            <p className={styles.p}>
                                MongoDB is a NoSQL database that stores data in
                                a flexible, JSON-like format, making it easy to
                                work with large volumes of unstructured data.
                            </p>
                            <button className={styles.btn}>Read More</button>
                        </div>
                    </div>
                </main>
                <footer className={styles.footer}></footer>
            </div>
        </>
    );
}
